from turtle import *

print (1,"even")
print (2, "odd")
print (3, "even")
print(4, "odd")
print(5, "even")
print(6, "odd")
print(7, "even")
print(8, "odd")
print(9, "odd")
print(10, "even")
print(11, "odd")
print(12, "even")
print(13, "odd")
print(14, "even")
print(15, "odd")
print(16, "even")
print(17, "odd")
print(18, "even")
print(19, "odd")
print(20, "even")
print(21, "odd")
print(22, "even")
print(23, "odd")
print(24, "even")
print(25, "odd" )
print(26, "even")
print(27, "odd" )
print(28, "even")
print(29, "Odd" )
print(30, "even" )